// Unit tests for the npm launcher's SHA-256 verification path.
//
// Uses node's built-in `node:test` runner so the test stays
// dependency-free (the launcher itself ships with zero deps, and we
// want the test to be runnable on the same minimal toolchain).
//
// We require launcher.cjs as a module so the launcher IIFE doesn't
// execute (`require.main === module` guards it). All side-effect-bearing
// code stays unexercised — these tests only hit the pure helpers.
//
// Run with: pnpm test:launcher  (root package.json)
//          node --test scripts/npm-launcher/launcher.test.mjs

import { test } from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));

const {
  parseChecksumsManifest,
  sha256File,
  verifyChecksum,
  detectAsset,
  downloadUrl,
  checksumsUrl,
} = require(join(__dirname, "launcher.cjs"));

// ─── parseChecksumsManifest ─────────────────────────────────────────────

test("parseChecksumsManifest — GNU two-space format", () => {
  const m = parseChecksumsManifest(
    "a".repeat(64) + "  0sec-linux-x64\n" + "b".repeat(64) + "  0sec-darwin-arm64\n",
  );
  assert.equal(m.size, 2);
  assert.equal(m.get("0sec-linux-x64"), "a".repeat(64));
  assert.equal(m.get("0sec-darwin-arm64"), "b".repeat(64));
});

test("parseChecksumsManifest — BSD binary-marker format ('<hex> *<name>')", () => {
  const m = parseChecksumsManifest("c".repeat(64) + " *0sec-windows-x64.exe\n");
  assert.equal(m.get("0sec-windows-x64.exe"), "c".repeat(64));
});

test("parseChecksumsManifest — ignores blank lines and # comments", () => {
  const txt = [
    "# generated by release workflow",
    "",
    "d".repeat(64) + "  0sec-linux-arm64",
    "",
  ].join("\n");
  const m = parseChecksumsManifest(txt);
  assert.equal(m.size, 1);
  assert.equal(m.get("0sec-linux-arm64"), "d".repeat(64));
});

test("parseChecksumsManifest — returns empty map for unparseable input", () => {
  const m = parseChecksumsManifest("this is not a checksums file\nnope\n");
  assert.equal(m.size, 0);
});

test("parseChecksumsManifest — lowercases UPPER-cased hex digests", () => {
  const m = parseChecksumsManifest("ABCDEF" + "0".repeat(58) + "  0sec-linux-x64\n");
  assert.equal(m.get("0sec-linux-x64"), "abcdef" + "0".repeat(58));
});

test("parseChecksumsManifest — throws TypeError on non-string input", () => {
  assert.throws(() => parseChecksumsManifest(undefined), TypeError);
  assert.throws(() => parseChecksumsManifest(123), TypeError);
});

// ─── verifyChecksum ─────────────────────────────────────────────────────

// Build a small fixture once and reuse it across the verifyChecksum
// tests. We deliberately use a small (~bytes) payload — verifyChecksum
// doesn't enforce a min size; that check lives in the launcher's
// ensureBinary() and is exercised by the install-smoke suite, not here.

const workdir = mkdtempSync(join(tmpdir(), "0sec-launcher-test-"));
const binaryPath = join(workdir, "0sec-linux-x64");
writeFileSync(binaryPath, Buffer.from("fake 0sec binary contents — node:test fixture"));
const binaryDigest = await sha256File(binaryPath);

test.after(() => {
  rmSync(workdir, { recursive: true, force: true });
});

test("verifyChecksum — happy path returns the digest", async () => {
  const manifest = `${binaryDigest}  0sec-linux-x64\n`;
  const got = await verifyChecksum({
    filePath: binaryPath,
    expectedAsset: "0sec-linux-x64",
    manifestText: manifest,
  });
  assert.equal(got, binaryDigest);
});

test("verifyChecksum — rejects on hash mismatch", async () => {
  const wrongHash = "0".repeat(64);
  const manifest = `${wrongHash}  0sec-linux-x64\n`;
  await assert.rejects(
    () =>
      verifyChecksum({
        filePath: binaryPath,
        expectedAsset: "0sec-linux-x64",
        manifestText: manifest,
      }),
    /SHA-256 mismatch/,
  );
});

test("verifyChecksum — rejects when manifest is empty / unparseable", async () => {
  await assert.rejects(
    () =>
      verifyChecksum({
        filePath: binaryPath,
        expectedAsset: "0sec-linux-x64",
        manifestText: "",
      }),
    /empty or unparseable/,
  );
});

test("verifyChecksum — rejects when manifest lacks expected asset", async () => {
  const manifest = `${binaryDigest}  0sec-darwin-arm64\n`;
  await assert.rejects(
    () =>
      verifyChecksum({
        filePath: binaryPath,
        expectedAsset: "0sec-linux-x64",
        manifestText: manifest,
      }),
    /no entry for "0sec-linux-x64"/,
  );
});

test("verifyChecksum — case-insensitive hex comparison", async () => {
  const manifest = `${binaryDigest.toUpperCase()}  0sec-linux-x64\n`;
  const got = await verifyChecksum({
    filePath: binaryPath,
    expectedAsset: "0sec-linux-x64",
    manifestText: manifest,
  });
  assert.equal(got, binaryDigest);
});

// ─── URL helpers ─────────────────────────────────────────────────────────

test("downloadUrl — points at the release tag", () => {
  const url = downloadUrl("0sec-linux-x64");
  // The launcher template substitutes __0SEC_VERSION__ at build
  // time; the un-substituted source-of-truth keeps the literal
  // placeholder. Either way the path shape must be a v<tag>/<asset>.
  assert.match(url, /^https:\/\/github\.com\/.+\/releases\/download\/v.+\/0sec-linux-x64$/);
});

test("checksumsUrl — same release tag as the binary URL", () => {
  const cu = checksumsUrl();
  const bu = downloadUrl("0sec-linux-x64");
  // Strip the differing trailing filename off each URL — if they
  // resolved to different release tags we'd be verifying against
  // a manifest from a different release, which is exactly the bug
  // we're guarding against.
  assert.equal(
    cu.replace(/checksums\.txt$/, ""),
    bu.replace(/0sec-linux-x64$/, ""),
  );
});

test("detectAsset — returns null or a known asset name", () => {
  const got = detectAsset();
  // detectAsset is platform-conditional; the only invariant we can
  // assert from inside vitest is that the return is either null or
  // one of the four supported asset filenames.
  if (got !== null) {
    assert.match(got, /^0sec-(darwin-arm64|linux-x64|linux-arm64|windows-x64\.exe)$/);
  }
});
