import { describe, expect, it } from "vitest";

import {
  adaptReproForDistro,
  detectReproFeatures,
  detectSubsystems,
  DISTRO_PROFILES,
} from "./distro-adapt.js";
import type { NativeRuntime } from "../runtime/types.js";

/**
 * A fixture upstream reproducer in the shape syzkaller emits: an options header
 * declaring sandbox=namespace + USB, plus C setup calls (loop device, raw USB).
 * The bug is in AF_RXRPC, matching one of the hunt targets (CVE-2026-43500).
 */
const UPSTREAM_RXRPC_REPRO = `// autogenerated by syzkaller
# {Threaded:true Repeat:true Sandbox:namespace NetInjection:true USB:true}
#include <sys/socket.h>

static void setup_loop_device(void) { /* ... */ }
static void setup_usb(void) { /* ... */ }

int main(void) {
  unshare(CLONE_NEWUSER | CLONE_NEWNS);
  setup_loop_device();
  setup_usb();
  int fd = socket(AF_RXRPC, SOCK_DGRAM, 0);
  return 0;
}
`;

describe("kernel/distro-adapt", () => {
  it("detects syzkaller features from the header and the C setup calls", () => {
    const features = detectReproFeatures(UPSTREAM_RXRPC_REPRO);
    // From the header: sandbox=namespace, NetInjection (tun+netdev), USB.
    expect(features).toContain("sandbox:namespace");
    expect(features).toContain("tun");
    expect(features).toContain("netdev");
    expect(features).toContain("usb");
    // From the C body setup calls.
    expect(features).toContain("loop_device");
  });

  it("identifies the vulnerable subsystem from the socket family", () => {
    expect(detectSubsystems(UPSTREAM_RXRPC_REPRO)).toContain("rxrpc");
  });

  it("surfaces the USB CONFIG delta as a blocker on Debian 12 (6.1.y)", async () => {
    const plan = await adaptReproForDistro(
      UPSTREAM_RXRPC_REPRO,
      { version: "6.10-rc4" },
      { version: "6.1.0-21-amd64", distro: "debian-12" },
    );

    expect(plan.toKernel).toBe("6.1.0-21-amd64");
    expect(plan.distro).toBe("debian-12");

    // KNOWN delta: stock Debian 12 does NOT build raw-gadget / dummy_hcd, so the
    // USB feature is a blocker requiring a CONFIG enable. This is the grounded
    // assertion the SyzBridge technique hinges on.
    const usbDelta = plan.configDeltas.find(
      (d) => d.config === "CONFIG_USB_RAW_GADGET",
    );
    expect(usbDelta).toBeDefined();
    expect(usbDelta?.severity).toBe("blocker");
    expect(usbDelta?.reason).toMatch(/Debian 12/);

    // AF_RXRPC is named as a subsystem-build check.
    expect(
      plan.configDeltas.some((d) => d.config === "CONFIG_AF_RXRPC"),
    ).toBe(true);

    // A loop-device precondition is surfaced for the harness.
    expect(plan.preconditions.some((p) => p.feature === "loop_device")).toBe(
      true,
    );
  });

  it("does NOT emit a userns runtime-sysctl blocker when the distro allows it", async () => {
    // Debian 12 enables unprivileged userns by default, so sandbox=namespace
    // should NOT produce a runtime-sysctl blocker (only the recommended CONFIG).
    const plan = await adaptReproForDistro(
      UPSTREAM_RXRPC_REPRO,
      { version: "6.10-rc4" },
      { version: "6.1.0-21-amd64", distro: "debian-12" },
    );
    expect(DISTRO_PROFILES["debian-12"]!.userNsUnprivilegedDefault).toBe(true);
    expect(
      plan.configDeltas.some(
        (d) => d.config === "kernel.unprivileged_userns_clone",
      ),
    ).toBe(false);
  });

  it("falls soft on an unknown distro profile (note, no crash)", async () => {
    const plan = await adaptReproForDistro(
      UPSTREAM_RXRPC_REPRO,
      { version: "6.10-rc4" },
      { version: "5.10.0", distro: "made-up-distro" },
    );
    expect(plan.notes.some((n) => n.includes("unknown distro profile"))).toBe(
      true,
    );
    // Without a profile every feature is treated as possibly-missing, so we
    // still get config deltas (no distro gating), proving fail-soft.
    expect(plan.configDeltas.length).toBeGreaterThan(0);
    expect(plan.llmAssisted).toBe(false);
  });

  it("merges LLM-suggested source adjustments without dropping deterministic deltas", async () => {
    const fakeLlm: NativeRuntime = {
      type: "api",
      isAvailable: async () => true,
      executeNative: async () => ({
        content: [
          {
            type: "text",
            text:
              '```json\n{"adjustments":[{"kind":"struct-rename",' +
              '"description":"rxrpc_call layout changed between 6.10 and 6.1"}],' +
              '"adjustedRepro":"// adjusted\\nint main(){return 0;}"}\n```',
          },
        ],
        stopReason: "end_turn",
        durationMs: 1,
      }),
    };

    const plan = await adaptReproForDistro(
      UPSTREAM_RXRPC_REPRO,
      { version: "6.10-rc4" },
      { version: "6.1.0-21-amd64", distro: "debian-12" },
      { llm: fakeLlm },
    );

    expect(plan.llmAssisted).toBe(true);
    expect(plan.reproAdjustments).toHaveLength(1);
    expect(plan.reproAdjustments[0]?.kind).toBe("struct-rename");
    expect(plan.adjustedRepro).toContain("// adjusted");
    // Deterministic USB blocker is still present alongside the LLM output.
    expect(
      plan.configDeltas.some((d) => d.config === "CONFIG_USB_RAW_GADGET"),
    ).toBe(true);
  });
});
