import { describe, it, expect } from "vitest";
import {
  fingerprintWaf,
  classifyResponse,
  runEvasionCampaign,
  jitterFor,
  EVASION_STRATEGIES,
  WafDetector,
  readHeader,
  type HttpRequestParts,
  type WafResponseLike,
} from "./waf-detect.js";

/**
 * Virtual clock for the adaptive-evasion loop. As with `rate-limit.test.ts`,
 * we never touch real `setTimeout` — every jitter sleep is intercepted and
 * recorded so the campaign finishes in microseconds and the pacing is
 * asserted deterministically.
 */
function virtualClock(start = 2_000_000) {
  let now = start;
  const sleeps: number[] = [];
  return {
    nowFn: () => now,
    sleepFn: async (ms: number) => {
      sleeps.push(ms);
      now += ms;
    },
    sleeps: () => sleeps,
  };
}

describe("readHeader", () => {
  it("reads from a fetch-style Headers bag case-insensitively", () => {
    const h = new Headers({ "CF-RAY": "abc-LHR" });
    expect(readHeader(h, "cf-ray")).toBe("abc-LHR");
    expect(readHeader(h, "missing")).toBeNull();
  });

  it("reads from a plain record case-insensitively", () => {
    const h = { Server: "cloudflare", "X-Foo": ["a", "b"] };
    expect(readHeader(h, "server")).toBe("cloudflare");
    expect(readHeader(h, "x-foo")).toBe("a, b");
    expect(readHeader(h, "nope")).toBeNull();
  });
});

describe("fingerprintWaf", () => {
  it("returns null when nothing matches", () => {
    expect(
      fingerprintWaf({ status: 200, headers: { server: "nginx" }, body: "hello" }),
    ).toBeNull();
  });

  it("fingerprints Cloudflare from the cf-ray header", () => {
    const fp = fingerprintWaf({
      status: 403,
      headers: { server: "cloudflare", "cf-ray": "7d-LHR" },
      body: "Attention Required! | Cloudflare",
    });
    expect(fp).not.toBeNull();
    expect(fp!.vendor).toBe("cloudflare");
    expect(fp!.confidence).toBeGreaterThan(0.5);
    expect(fp!.signals.some((s) => s.kind === "header")).toBe(true);
  });

  it("fingerprints AWS WAF from x-amzn headers", () => {
    const fp = fingerprintWaf({
      status: 403,
      headers: { "x-amzn-requestid": "abc", "x-amzn-waf-action": "block" },
      body: "Request blocked",
    });
    expect(fp!.vendor).toBe("aws-waf");
  });

  it("fingerprints Imperva/Incapsula from a Set-Cookie", () => {
    const fp = fingerprintWaf({
      status: 403,
      headers: { "set-cookie": "visid_incap_12345=abcd; path=/" },
      body: "Incapsula incident ID: 999",
    });
    expect(fp!.vendor).toBe("imperva-incapsula");
    expect(fp!.signals.some((s) => s.kind === "cookie")).toBe(true);
  });

  it("fingerprints ModSecurity from the body alone", () => {
    const fp = fingerprintWaf({
      status: 406,
      headers: {},
      body: "<title>Not Acceptable!</title> This error was generated by Mod_Security",
    });
    expect(fp!.vendor).toBe("modsecurity");
  });

  it("reads Set-Cookie via getSetCookie() when present", () => {
    const headers = {
      get: (_n: string) => null,
      getSetCookie: () => ["__cf_bm=xyz; path=/"],
    } as unknown as Headers;
    const fp = fingerprintWaf({ status: 403, headers, body: "" });
    expect(fp!.vendor).toBe("cloudflare");
  });
});

describe("classifyResponse", () => {
  it("does not flag a legitimate 200", () => {
    const v = classifyResponse({ status: 200, headers: { server: "nginx" }, body: "<html>ok</html>" });
    expect(v.blocked).toBe(false);
  });

  it("flags a fingerprinted vendor + block status as blocked", () => {
    const v = classifyResponse({
      status: 403,
      headers: { "cf-ray": "7d-LHR", server: "cloudflare" },
      body: "Attention Required! | Cloudflare",
    });
    expect(v.blocked).toBe(true);
    expect(v.fingerprint!.vendor).toBe("cloudflare");
    expect(v.reason).toMatch(/Cloudflare/);
  });

  it("flags a generic block marker on a 403 even without a vendor", () => {
    const v = classifyResponse({
      status: 403,
      headers: {},
      body: "The requested URL was rejected. Please consult with your administrator.",
    });
    expect(v.blocked).toBe(true);
    expect(v.fingerprint).toBeDefined();
  });

  it("treats HTTP 429 as a block (edge throttle)", () => {
    const v = classifyResponse({ status: 429, headers: {}, body: "slow down" });
    expect(v.blocked).toBe(true);
    expect(v.reason).toMatch(/429/);
  });

  it("flags a browser-challenge interstitial served with 200", () => {
    const v = classifyResponse({
      status: 200,
      headers: { server: "cloudflare", "cf-ray": "x" },
      body: "Just a moment... Checking your browser before accessing.",
    });
    expect(v.blocked).toBe(true);
  });

  it("does NOT flag a fingerprinted WAF when the response looks legitimate", () => {
    const v = classifyResponse({
      status: 200,
      headers: { server: "cloudflare", "cf-ray": "x" },
      body: "<html>welcome to the app</html>",
    });
    expect(v.blocked).toBe(false);
    expect(v.fingerprint!.vendor).toBe("cloudflare");
  });
});

describe("evasion strategies", () => {
  const base: HttpRequestParts = {
    url: "https://t.example.com/search?q=1%20UNION%20SELECT%20password%20FROM%20users",
    method: "GET",
    headers: { "X-Test": "1" },
  };

  it("percent-encode-params changes the query value", () => {
    const s = EVASION_STRATEGIES.find((x) => x.name === "percent-encode-params")!;
    const out = s.apply(base);
    expect(out.changed).toBe(true);
    // The literal "UNION" / "SELECT" keywords should no longer appear verbatim.
    expect(out.parts.url).not.toMatch(/UNION/i);
    expect(out.parts.url).toMatch(/%/);
  });

  it("case-fold-keywords reshapes SQL keywords", () => {
    const s = EVASION_STRATEGIES.find((x) => x.name === "case-fold-keywords")!;
    const parts: HttpRequestParts = { url: "https://t.example.com/", method: "POST", headers: {}, body: "id=1 UNION SELECT 1" };
    const out = s.apply(parts);
    expect(out.changed).toBe(true);
    expect(out.parts.body).not.toContain("UNION");
    // Same letters, different casing — semantically identical SQL.
    expect(out.parts.body!.toUpperCase()).toContain("UNION SELECT");
  });

  it("inline-comment-keywords splits keywords with /**/", () => {
    const s = EVASION_STRATEGIES.find((x) => x.name === "inline-comment-keywords")!;
    const parts: HttpRequestParts = { url: "https://t.example.com/", method: "POST", headers: {}, body: "x=union" };
    const out = s.apply(parts);
    expect(out.parts.body).toContain("/**/");
  });

  it("header-casing varies header names and adds X-Forwarded-For", () => {
    const s = EVASION_STRATEGIES.find((x) => x.name === "header-casing")!;
    const out = s.apply(base);
    expect(out.changed).toBe(true);
    expect(out.parts.headers["X-Forwarded-For"]).toBe("127.0.0.1");
  });

  it("a strategy reports changed=false when it is a no-op", () => {
    const s = EVASION_STRATEGIES.find((x) => x.name === "inline-comment-keywords")!;
    const parts: HttpRequestParts = { url: "https://t.example.com/plain", method: "GET", headers: {} };
    const out = s.apply(parts);
    expect(out.changed).toBe(false);
  });
});

describe("jitterFor", () => {
  it("is deterministic and increases with attempt number by default", () => {
    expect(jitterFor(0, 200)).toBe(200);
    expect(jitterFor(1, 200)).toBe(400);
    expect(jitterFor(2, 200)).toBe(600);
  });

  it("uses injected rng for full-jitter when provided", () => {
    expect(jitterFor(1, 100, () => 0.5)).toBe(Math.floor(0.5 * 100 * 2));
  });
});

describe("runEvasionCampaign", () => {
  const blocked: WafResponseLike = {
    status: 403,
    headers: { "cf-ray": "x", server: "cloudflare" },
    body: "Attention Required! | Cloudflare",
  };
  const ok: WafResponseLike = { status: 200, headers: {}, body: "<html>ok</html>" };

  const parts: HttpRequestParts = {
    url: "https://t.example.com/q?x=1%20UNION%20SELECT%201",
    method: "GET",
    headers: { "X-A": "1" },
  };

  it("bypasses on the first strategy that returns a non-blocked response", async () => {
    const c = virtualClock();
    let calls = 0;
    const campaign = await runEvasionCampaign(
      parts,
      async () => {
        calls += 1;
        return ok; // first variant already slips through
      },
      { sleepFn: c.sleepFn },
    );
    expect(campaign.bypassed).toBe(true);
    expect(campaign.bypassStrategy).toBe("percent-encode-params");
    expect(calls).toBe(1);
    // One jitter sleep was paced before the (single) attempt.
    expect(c.sleeps().length).toBe(1);
    expect(campaign.final.status).toBe(200);
  });

  it("walks the ladder and gives up when every variant stays blocked", async () => {
    const c = virtualClock();
    let calls = 0;
    const campaign = await runEvasionCampaign(
      parts,
      async () => {
        calls += 1;
        return blocked;
      },
      { sleepFn: c.sleepFn },
    );
    expect(campaign.bypassed).toBe(false);
    expect(campaign.bypassStrategy).toBeNull();
    // Every strategy that actually mutated the request was attempted.
    expect(calls).toBeGreaterThanOrEqual(1);
    expect(campaign.attempts.length).toBe(EVASION_STRATEGIES.length);
    // Jitter increases (backoff) across real attempts.
    const paced = c.sleeps();
    expect(paced.length).toBe(calls);
  });

  it("succeeds on a later strategy and records all prior attempts", async () => {
    const c = virtualClock();
    let calls = 0;
    const campaign = await runEvasionCampaign(
      parts,
      async () => {
        calls += 1;
        // First two real attempts blocked, third slips through.
        return calls >= 3 ? ok : blocked;
      },
      { sleepFn: c.sleepFn },
    );
    expect(campaign.bypassed).toBe(true);
    expect(calls).toBe(3);
    const realAttempts = campaign.attempts.filter((a) => a.jitterMs > 0 || a.note !== "skipped (no-op for this request)");
    expect(realAttempts.length).toBe(3);
    expect(campaign.attempts.at(-1)!.blocked).toBe(false);
  });

  it("honours maxAttempts", async () => {
    const c = virtualClock();
    let calls = 0;
    const campaign = await runEvasionCampaign(
      parts,
      async () => {
        calls += 1;
        return blocked;
      },
      { sleepFn: c.sleepFn, maxAttempts: 2 },
    );
    expect(campaign.attempts.length).toBe(2);
    expect(campaign.bypassed).toBe(false);
  });
});

describe("WafDetector", () => {
  it("records blocks per host and upgrades to higher-confidence fingerprints", () => {
    const clock = virtualClock();
    const d = new WafDetector({ nowFn: clock.nowFn });
    const url = "https://shop.example.com/x";

    // First: a weak (body-only) detection.
    d.recordBlock(url, classifyResponse({ status: 403, headers: {}, body: "access denied" }));
    // Then: a strong header+cookie Cloudflare detection.
    d.recordBlock(url, classifyResponse({
      status: 403,
      headers: { "cf-ray": "x", server: "cloudflare", "set-cookie": "__cf_bm=z" },
      body: "Attention Required! | Cloudflare",
    }));

    const states = d.hostStates();
    expect(states).toHaveLength(1);
    expect(states[0].host).toBe("shop.example.com");
    expect(states[0].vendor).toBe("cloudflare");
    expect(states[0].blockCount).toBe(2);
    expect(d.isKnownWafHost("https://shop.example.com/other")).toBe(true);
    expect(d.isKnownWafHost("https://other.example.com/")).toBe(false);
  });

  it("records evasion evidence with authorized-engagement provenance", async () => {
    const clock = virtualClock();
    const d = new WafDetector({ nowFn: clock.nowFn });
    const url = "https://api.example.com/q?x=1";
    const verdict = classifyResponse({ status: 403, headers: { "cf-ray": "x" }, body: "blocked" });
    d.recordBlock(url, verdict);
    const campaign = await runEvasionCampaign(
      { url, method: "GET", headers: {} },
      async () => ({ status: 200, headers: {}, body: "ok" }),
      { sleepFn: clock.sleepFn },
    );
    d.recordEvasion(url, verdict, campaign);

    const evidence = d.evidence();
    expect(evidence).toHaveLength(1);
    expect(evidence[0].authorizedEngagement).toBe(true);
    expect(evidence[0].bypassed).toBe(true);
    expect(evidence[0].host).toBe("api.example.com");

    const summary = d.summary();
    expect(summary.waf_detected).toBe(true);
    expect(summary.total_blocks).toBe(1);
    expect(summary.total_bypasses).toBe(1);
  });

  it("caps the evidence log", async () => {
    const clock = virtualClock();
    const d = new WafDetector({ nowFn: clock.nowFn, maxEvidence: 2 });
    const verdict = classifyResponse({ status: 403, headers: {}, body: "access denied" });
    const campaign = await runEvasionCampaign(
      { url: "https://h.example.com/", method: "GET", headers: {} },
      async () => ({ status: 403, headers: {}, body: "access denied" }),
      { sleepFn: clock.sleepFn, maxAttempts: 1 },
    );
    for (let i = 0; i < 5; i++) d.recordEvasion(`https://h${i}.example.com/`, verdict, campaign);
    expect(d.evidence().length).toBe(2);
  });
});
